input.onButtonPressed(Button.A, function () {
    OLED.init(128, 64)
    music.startMelody(music.builtInMelody(Melodies.Dadadadum), MelodyOptions.Once)
    OLED.writeStringNewLine("What do you call a fish with no eyes?")
    music.startMelody(music.builtInMelody(Melodies.Dadadadum), MelodyOptions.Once)
    music.startMelody(music.builtInMelody(Melodies.Dadadadum), MelodyOptions.Once)
    OLED.writeStringNewLine("A FSH!")
    music.startMelody(music.builtInMelody(Melodies.Wawawawaa), MelodyOptions.Once)
    OLED.writeStringNewLine("What do you call a cheese that isn't yours!")
    music.startMelody(music.builtInMelody(Melodies.Wawawawaa), MelodyOptions.Once)
    OLED.writeStringNewLine("NACHO CHEESE!")
    OLED.writeStringNewLine("made by kyle ")
})
OLED.init(128, 64)
OLED.writeStringNewLine("bengals on top, press A you dinglebarry")
